version: "3.7"
services:
  #proxy:
   # build:
    #  context: proxy
    #depends_on:
    #  - webapp
    #command: ["./wait-for-it.sh", "--timeout=0", "drug-interaction_webapp_1:8888", "--", "nginx", "-g", "daemon off;"]
    #tty: true
    #ports:
     # - '443:443'
      #- '80:80'
  webapp:
    build: ./api/
    image: road2h-tmrweb
    container_name: tmrweb
    restart: unless-stopped
    #expose: 
    #  - 8888
    ports:
      - "8888:8888"
    networks: 
      - cig_handler
    environment:
      - JENA_HOST=fuseki
      - PROLOG_HOST=swipl
      - JENA_PORT=3030
      - PROLOG_PORT=1234
      - PORT=8888
      - FUSEKI_PASSWORD=road2h
    depends_on:
      - swipl
  swipl:
    build: ./backend/
    image: road2h-swipl
    container_name: swipl
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #expose:
    #  - 1234
    ports: 
      - "1234:1234"
    networks: 
      - cig_handler
    environment:
      - FUSEKI_HOST_PORT=http://fuseki:3030/
    depends_on: 
      - fuseki
  busybox:
    image: busybox
    container_name: fuseki-data
    #restart: unless-stopped
    networks: 
      - cig_handler
    volumes: 
      - "drug_volume:/fuseki"
  fuseki:
    build: ./fuseki/
    image: road2h-fuseki
    container_name: fuseki
    restart: unless-stopped
    #expose: 3030
    ports: 
      - "3030:3030"
    networks: 
      - cig_handler
    #volumes_from: 
    #  - drug_volume
    environment:
      - ADMIN_PASSWORD=road2h
      - TDB=2
      - FUSEKI_DATASET_1=careActions
      - FUSEKI_DATASET_2=transitions
      - FUSEKI_DATASET_3=beliefs
      - FUSEKI_DATASET_4=CIG-COPD
      - JVM_ARGS=-Xmx2g
    depends_on: 
      - busybox
volumes:
  drug_volume: {}
networks:
  cig_handler: {}
