version: '3.8'

services:
  busybox:
    image: busybox
    container_name: fuseki-data
    networks: 
      - cig_handler
    volumes: 
      - "drug_volume:/fuseki"
    
  store_app:
    image: stain/jena-fuseki:5.1.0  # Pin to a specific version
    container_name: store_service
    restart: unless-stopped
    ports: 
      - "3030:3030"
    networks: 
      - cig_handler
    environment:
      - ADMIN_PASSWORD=road2h
      - TDB=2
      - FUSEKI_DATASET_1=careActions
      - FUSEKI_DATASET_2=transitions
      - FUSEKI_DATASET_3=beliefs
      - FUSEKI_DATASET_4=statements
      - JVM_ARGS=-Xmx2g
    depends_on: 
      - busybox
  
  interaction_app:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    image: road2h-interaction_ms
    container_name: interaction_service
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks: 
      - cig_handler
    environment:
      - JENA_HOST=store_service
      - PROLOG_HOST=reasoner_service
      - JENA_PORT=3030
      - PROLOG_PORT=1234
      - PORT=8888
      - FUSEKI_PASSWORD=road2h
    depends_on:
      - reasoner_app

  reasoner_app:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    image: road2h-reasoner_ms
    container_name: reasoner_service
    restart: unless-stopped
    stdin_open: true  # Keep container interactive
    tty: true         # Allocate a pseudo-TTY
    ports: 
      - "1234:1234"
    networks: 
      - cig_handler
    environment:
      - FUSEKI_HOST_PORT=http://store_service:3030/
    depends_on: 
      - store_app

volumes:
  drug_volume: {}

networks:
  cig_handler: {}
