version: "3.7"
services:
  #proxy:
   # build:
    #  context: proxy
    #depends_on:
    #  - webapp
    #command: ["./wait-for-it.sh", "--timeout=0", "drug-interaction_webapp_1:8888", "--", "nginx", "-g", "daemon off;"]
    #tty: true
    #ports:
     # - '443:443'
      #- '80:80'
  webapp:
    container_name: tmrweb
    image: tmrweb_img
    build:
      context: ./api/
    environment:
      - JENA_HOST=fuseki
      - PROLOG_HOST=swipl
    depends_on: [backend]

  backend:
    build:
      context: ./backend/
    environment:
      - FUSEKI_HOST_PORT=http://fuseki:3030/
    depends_on: [fuseki]

  fuseki:
    build:
      context: ./fuseki/
    volumes:
      - drug_volume:/fuseki
    environment:
      - ADMIN_PASSWORD=road2h

volumes:
  drug_volume:
networks:
  tmrNetwork:
