apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
        - name: store-app
          image: stain/jena-fuseki:5.1.0
          ports:
            - containerPort: 3030
          env:
            - name: ADMIN_PASSWORD
              value: "road2h"
            - name: TDB
              value: "2"
            - name: FUSEKI_DATASET_1
              value: "careActions"
            - name: FUSEKI_DATASET_2
              value: "transitions"
            - name: FUSEKI_DATASET_3
              value: "beliefs"
            - name: FUSEKI_DATASET_4
              value: "statements"
            - name: JVM_ARGS
              value: "-Xmx2g"
          volumeMounts:
            - name: fuseki-data
              mountPath: /fuseki
      volumes:
        - name: fuseki-data
          persistentVolumeClaim:
            claimName: fuseki-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  ports:
    - port: 3030
  selector:
    app: store-app