apiVersion: v1
kind: Service
metadata:
  name: interaction-service
spec:
  selector:
    app: interaction-app
  ports:
    - name: http
      protocol: TCP
      port: 8888 #external port
      targetPort: 8888 #internal port
      nodePort: 32030 #accessible outside the cluster
  type: NodePort 