apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: store-app
  ports:
    - name: http
      protocol: TCP
      port: 3030
      targetPort: 3030
  type: ClusterIP